### PR TITLE
Solo 207a Move globals

### PR DESCRIPTION
**Pull request by MatzElectronics**
Moves some globals into the global.js file.  This does not move any globals variables that would be affected by #200 or other upcoming issues/goals (variables that will likely/eventually be wrapped into classes/objects).

This also removes find and replace buttons in the experimental propc editor.  When the ace editor was updated last, it came with an internal find/replace UI, so the one that we created is no longer necessary.

### CODE REVIEW

**Comment by zfi** [comment]
There are actually several changes in this PR not directly related to #207. 

There are two global variables that are initialized from metadata provided by an HTML page. Before they can be moved to global.js, we need to ensure that there is matching metadata in all HTML pages.

**Comment by MatzElectronics** [comment]
Okay - both meta tags have been added to index.html.

**Comment by pjewald** [comment]
Please remove the changes not related to #207 and resubmit.

**Comment by MatzElectronics** [comment]
@pjewald resubmitting

**Pull request merged**
