### PR TITLE
Solo 265 add tilt to LIS3DH read block

### PR DESCRIPTION
**Pull request by MatzElectronics**
Addresses #265 

Adds tilt sensing to the LIS3DH read block.

**To test:**
Create a programs using each combination of init, read, and temperature blocks.
Try also using multiple init blocks.
Save and reopen projects using LIS3DH blocks.
Make sure field values are retained when blocks are reopened.
Make sure blocks generate working/usable C code.

### CODE REVIEW

**Comment by zfi** [comment]
@MatzElectronics, is this complete now?

**Comment by MatzElectronics** [comment]
I still have 1 more test I need to run, hopefully tomorrow, but everything is green on my end so far and I would strongly recommend getting this in at least one other person's hands to test due to the sheer complexity of the block mutators.

**Comment by zfi** [comment]
We'll bring it in when you are satisfied that it's working as designed.

**Comment by MatzElectronics** [comment]
Ugh - sorry, found another bug.  I'll keep working through it and keep everyone posted.

**Comment by MatzElectronics** [comment]
Okay - fingers crossed - I think I've gotten it all working.  I've run lots of tests on my end, trying lots of possible configurations of blocks as well as making sure they all generate working code.

Any strangeness that may still appear should be relegated to cases where there are multiple init blocks (multiple sensors) - which is likely a rare use case.  Additionally, simply moving a block or reselecting an option on the menu would likely be enough for the blocks to correct themselves - most of the bugginess was due to complex conditional sets in the mutator and by initialing an additional change, the mutator gets an opportunity to reset all of the blocks fields.

That being said, please test throughly.

**Pull request closed without merging**
