### PR TITLE
Solo 279-B Add connection messages

### PR DESCRIPTION
**Pull request by MatzElectronics**
Continues addressing #279 
Adds/improves messages related to the console/device connection in the UI.

### CODE REVIEW

**Comment by zfi** [comment]
There are two new messages in the submission. Where is the code that will reference them?

**Comment by MatzElectronics** [comment]
I will submit that in a later PR.  Just submitting these because there is
no harm in just adding a few constants.

**Comment by zfi** [comment]
While I agree that there is no harm, I would prefer to keep the messages linked up with the code that will reference them. That will avoid stragglers and give whomever is looking at this later a better sense of the change.

**Comment by MatzElectronics** [comment]
Okay, I'll add a commit or two to the PR.  Just taking a while to try to
break apart and re-order everything that I did in the original body of work.

**Comment by MatzElectronics** [comment]
Okay - they are in place.

**Pull request merged**
