### PR TITLE
Solo 263 fix type error in array block

### PR DESCRIPTION
**Pull request by MatzElectronics**
Code generation (`Blockly.propc.valueToCode`) should not be used inside of a block definition.  It was being used to see if the connected block contained a number value.  This replaces that code with code that looks for the **math_number** block and if found, it's field value.

### CODE REVIEW

**Comment by pjewald** [comment]
This error was introduced back in October, 2019 as part of PR #108.

**Comment by MatzElectronics** [comment]
I know better now...

**Comment by pjewald** [comment]
This patch addresses Solo #263

**Comment by MatzElectronics** [comment]
Looks like it was there before - #108 just rearranged it.

**Pull request merged**
