### PR TITLE
Solo 134 improve file downloading

### PR DESCRIPTION
**Pull request by MatzElectronics**
Addresses #134 and #118 

Replaces all code that packages and triggers file downloads with FileSaver.js, which is more robust and has better cross-browser compatibility.

Since SimpleIDE projects are two files, the download is now a single zipped folder containing both files (#134).

This removes the prompt that asked for a filename, and simply uses a sanitized version of the project name as the filename (#118).

Replaces all `alert()` calls with `utils.showMessage()`, and moves the strings into the internationalization file, since I was in this vicinity anyway.

### CODE REVIEW

**Comment by MatzElectronics** [comment]
#118 was a pure deletion.  It's easy enough to back that one back out if you'd like.  You had mentioned that strings all need to be in the messages file and that alerts should all use bootboxes from utils - since I was in the neighborhood, I just did a find/replace on the all, then a quick test to verify.
FWIW, I knew exactly what needed to be changed here, and this whole PR only took 1.25 hr.

Since this involved bringing in filesaver.js, I applied it wherever there was a download for consistency.

**Comment by pjewald** [comment]
@MatzElectronics: Did you verify that all of the dialogs that replaced the alerts are actually working as expected?

**Comment by MatzElectronics** [comment]
Yes I did.

**Comment by pjewald** [comment]
Thanks!

**Pull request merged**
